plugins { id 'com.android.application' }
android {
    namespace 'lan.classic.android'
    compileSdk 35
    defaultConfig {
        applicationId 'studio.reverfyx.classiclan'
        minSdk 16
        targetSdk 28
        versionCode 1
        versionName '0.1.0'
    }
    compileOptions { sourceCompatibility JavaVersion.VERSION_1_8; targetCompatibility JavaVersion.VERSION_1_8 }
    lint { abortOnError true; checkOnly 'NewApi', 'InlinedApi' }
    buildTypes { debug { minifyEnabled false } }
}
dependencies { implementation project(':core') }
